repos:
  # Black configuration
  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use the stable version of Black
    hooks:
      - id: black
        language_version: python3  # Optional: specify Python version

  # Mypy configuration
  # - repo: https://github.com/pre-commit/mirrors-mypy
    # rev: v0.971  # Specify the version of mypy
    # hooks:
      # - id: mypy
        # language_version: python3  # Optional: specify Python version
# 
  # Isort configuration
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Specify the version of isort
    hooks:
      - id: isort
        language_version: python3  # Optional: specify Python version

